In [1]:
# Import the dependencies.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Create a set of random latitude and longitude combinations.
lats = np.random.uniform(low=-90.000, high=90.000, size=1500)
lngs = np.random.uniform(low=-180.000, high=180.000, size=1500)
lat_lngs = zip(lats, lngs)
lat_lngs

In [3]:
# Add the latitudes and longitudes to a list.
coordinates = list(lat_lngs)

In [4]:
# Use the print() function to display the latitude and longitude combinations.
for coordinate in coordinates:
    print(coordinate[0], coordinate[1])

-25.981198580769473 36.78912940858649
65.01108700895571 129.812101842108
9.98384780383661 26.067974303524892
14.669330267465313 52.33190066315731
56.63801576603797 -6.690765892755763
-41.55894452250272 31.150003391691598
-4.014106263287886 -59.70167675035162
29.924723372233842 23.54824266501788
35.7301276232414 133.05825024388844
-64.75386035306767 16.254840791993644
-22.726546336309468 106.16400930330406
-31.262400363947066 75.85679852381702
-47.64922117438737 64.76042768505346
57.24731097813313 -127.343555240064
-27.908494365810384 -153.2810107821987
19.537340919163626 -78.745581280373
-16.601119057177996 -19.742659005386287
89.67078502243064 -67.5931835326438
-59.17884108943114 -46.625175411629044
-64.81136219119888 177.11851680450826
25.53010101493868 -62.31434690140756
28.956903324932682 5.184498025762252
25.95095132478771 -151.22237240222086
-7.146358092101167 67.99581455693075
33.10290038077865 18.74583802283064
27.271271682292223 -155.16597767581732
-78.283163520297 -112.31788962292748
-7.142614611580356 -101.77615111559736
86.7249417554975 -35.305829772362245
29.836294079940572 -124.71072458065828
26.36420998028396 168.61708289442555
-11.795079536739948 124.0740390635101
72.62618687860035 -99.16159939396829
59.90672328432018 150.8048044313993
-77.87717721950675 113.60036554140356
-76.7980610175413 1.2214633274597588
-25.99098301829794 52.23779345089264
-4.798770527107436 72.84799567332826
19.31791796451202 55.22396842118715
-4.540450197762539 63.70665869254674
41.28417459688015 72.18282732025077
-83.1659780547024 -96.69287708621002
-8.933637787937428 35.82478465188677
13.040852180184132 154.09327490548986
-63.82268616836541 11.04938503265248
4.440778846989687 -152.3358744904182
-33.54441664677239 -22.701870166884106
-33.74046864448283 -15.127826958740457
-73.04813870576837 -81.12837530796521
12.672846627737442 97.48232679761446
84.2780712195516 -164.94820646390204
-86.79514622572131 45.38529515974224
-38.53759372578852 102.94624709771034
-64.86271473114445 -139.31779592676503
-77.72987169627714 53.848843767955
20.756064742355605 -173.83840304464093
57.547828368629524 31.15148754387738
-81.86772341911325 2.5777316448589147
45.24256476629782 110.70947506932538
-67.71863313965673 -87.9550492392677
-56.115207928042516 54.53206516707459
3.415370766579784 -162.69735953652216
81.70602864262145 -36.400847082427816
-63.59498744605929 92.60694817021135
47.55275414620883 -69.72516346574821
-83.0036576215114 153.57488523411178
-57.00173413975803 17.643446673070173
88.62592972957387 -57.16058445709389
15.908874500318177 53.90680738904808
81.28693127379515 -35.62460752759671
35.54950088864655 -119.04211220589575
-6.077638300347559 115.79347491666624
58.803168240614525 -101.38785408414243
-34.21260380553438 132.72208007865748
-65.65474330063476 12.319731268550441
-70.91519875764325 108.45428402033684
-32.87083196485538 119.40363870909073
40.615852519671876 -72.57463444717483
23.247350700652078 171.60537731403957
55.91422652503576 -29.05886429434304
-22.75512470356611 -164.98821904971587
-23.443565323901936 74.44517379880352
40.15271072962565 81.72979376949655
-22.90766499836714 179.32580937751192
-42.38907517467793 136.68000648029107
-45.21887135956044 149.3710944670599
-19.683105353236684 24.07952659801893
50.43091239705956 51.2553387175256
68.3499839027472 63.62285458593675
-43.366494565843226 21.06695101184752
-30.543445277736957 -79.11857470432207
87.16871130576635 74.15680997738988
-86.9995402126307 90.88806697218979
-10.856704328347504 -92.48136766863092
-59.17602469020366 -73.27542487940009
-88.36451838595977 -1.091473345621182
-51.917501777072744 -96.06352255998712
56.93531386291204 -92.86187212735466
45.15423388725324 -176.62074719258172
-17.10092188720195 162.54854795615256
-24.073728192310384 18.07835654548697
24.24795993416629 175.57336195836018
-62.55170162511476 82.24798523879832
77.41844711607837 83.21196504977269
-16.3595420094953 69.16919763560287
-81.11648381344258 1.9177321824219007
64.45914214836813 109.12380609551764
-73.8491838502475 -49.523584839238026
-19.46631619732291 121.21424669037776
-58.733384933235506 -128.61734069676214
-62.759049437109425 116.5422383479073
44.105267309102715 -68.65817973994012
-23.620943235214753 35.788052630226616
62.190819759438654 79.18298352994026
-62.28232224597609 172.48280231949826
-73.36497818783768 -159.9620130107325
23.765916251066585 -26.027909839428844
-28.554284056360387 -175.74046002385737
68.72576867302084 -133.32008776925701
-59.3706873571671 144.90111216750296
-37.17176343723294 72.8961665461728
-75.3819182320152 -106.03241484238667
51.84652862634755 -84.40514581319572
-11.185363276908248 -29.645276474669913
-20.30046702696552 137.67144361414034
86.81597733392275 73.26512418945029
20.66813493969093 36.16634405916304
54.239715580016394 -58.30098226470561
15.305145252698594 156.01203357433712
-47.159597423748686 66.57220383847408
-43.9730607459503 76.56023634134391
75.09544911668789 152.6736360925355
-63.785511231655335 -0.8605385012049567
-84.88169861645994 143.08573509119555
-76.09467620264815 154.50024969383867
35.52482654849578 -98.36177452969619
-5.4749992848488205 173.07577881229975
-63.62376252756715 147.27067830732528
54.54515208861133 156.05015621630645
35.06493302417566 165.04208085034617
66.97305923392739 108.92346255523216
6.6610675370230865 147.65734770384262
14.438115685222044 -112.31932952973915
-0.38745765363087514 79.76176707736664
-2.77044050295909 45.83485148732407
68.9722828614789 -160.51162760067027
-36.82359124361991 26.806946917187332
-74.56601536800608 138.1052551647033
-17.171958011352473 85.23235709054262
43.60369742030454 -178.88887220779495
81.12335092411314 54.69174799917681
4.216697099593574 -42.29916357876158
-18.228898332066947 -84.0648873994496
19.159599945085347 42.54043741139438
50.45022779977455 -107.00159873383465
-71.35457172765823 -106.12383276309595
4.717997849771791 116.99346423124899
-41.58634837093865 135.8606723727736
-32.5808603006812 -113.90823224992761
12.267766458491366 25.324267029989926
35.4072670512667 54.62209238499938
-34.2423502908408 -157.0953219004071
28.279211676987245 167.62816833242084
67.14153106818671 149.8352800848815
78.00585617223314 -0.27543822295928067
55.58138917186122 -92.04698875556112
-52.27264281360161 -167.26431326491388
-53.73259906363968 144.21600410888647
81.58831583455498 34.772429395860286
42.901575275038454 -110.70934709289816
-4.129606190604321 -105.761193567873
38.92910005570471 -126.92382941981691
22.541575084341574 85.34226688566054
-7.515242850214548 -99.95920061171994
23.547492930937295 -31.211949438308324
28.645491530554594 -22.848702141290943
-2.9305840919665656 165.7770656948789
-33.40119870733478 -37.52400221226043
22.973996076306634 -97.0833722098194
82.20071367828811 27.473423493571772
-5.065077271110837 46.13727987046218
-9.827183784890181 -31.46386763444596
55.095072817184956 145.47246046200564
51.102024597999986 -160.39576283335697
-16.079377301282094 -55.994488049549176
62.12298692252696 -42.47672792573056
38.91624117341905 147.73257129643093
58.089372949977786 -161.6361697427883
85.40827553728624 69.97943989460424
-20.61630408296577 -96.15666211474807
5.854920770002224 71.19520101575208
16.040117610110556 117.27063801051895
40.82847505944156 -147.6267011263153
3.8323052889524405 -158.05919855984766
-72.21555125309972 49.10453793210871
-44.8106253141183 166.49826958120212
15.282379319378549 167.9447279694284
64.56038900316585 130.34391798917306
59.892685110392165 0.697590181730817
34.846886785507834 -121.26411998621478
66.11020826866849 35.89688997715206
27.99482350024701 7.4677839043745
-83.28770636307924 137.73584847096788
-23.30066834185928 94.52459981162673
24.54720240633415 -132.9951603796105
-37.89895578191077 15.878876992162702
-61.26207533215606 -94.48627772811
-21.47782694770187 155.40519422991588
-86.67752149871733 -151.56120818081442
35.82547371981428 5.86827926263868
29.657695789692426 -167.6299623759477
88.44582797759796 56.36303525626326
26.922728255506357 -137.02813136901992
43.073185697766775 95.92602730053886
-87.69386116922112 -65.12007373433575
-74.18186997505694 75.49509188206073
57.155012841779325 146.61666608581095
-30.241786549982898 63.98453108537487
-45.73145153724461 -117.9783296350108
-34.084325592325094 40.129321834148044
-22.740928647276803 -14.677026743896562
61.864483880507635 37.359345838345746
32.56369962817381 20.50042477714797
48.62629699505493 108.45010059911124
-47.10251453108506 119.85346157492461
-21.995330083266794 102.26552075792426
-0.2245255475470458 -28.192330399037928
-77.70893497315137 81.2948946839619
-88.7604929086453 -4.0660114805873775
-78.61531758529394 -117.30956219754705
-44.96902034330116 -114.81412812388524
22.6501924129756 -96.6596328808557
36.044772304802024 -28.820399332425495
2.787402465031036 93.87109443819617
68.81828666329142 105.06483645712154
-69.98100544981423 114.30990675972174
76.46900795648574 -46.70782218292905
-20.90455919924564 -152.264105419007
-31.00931486354049 -129.8905617084472
19.05702445858462 -104.78543603881036
67.34116261110253 -141.19261228488313
51.30681101978644 107.7432610466534
-39.68362390360458 -11.531716748246964
-49.42333934100769 130.98814341926135
-56.305996740993564 119.81859941414808
-13.408100596473602 -89.45958855844252
-41.311777983411865 38.29884713391428
-45.68113720256993 -133.16512044253744
-44.13570954236961 -11.05715195669535
-23.25263079226184 111.09536613618769
87.9740286666514 -56.92346040216192
17.34677715734415 -178.8671529946545
15.382533979275294 13.927614466625784
-33.99857094898857 -121.4886823565547
-21.041715339255063 -123.44688586483402
-5.100637355156067 179.22631679107633
28.761744081595666 -141.41636739752695
-30.348374961165632 13.114712339202129
-47.16289820346306 -115.99665964041553
-18.97300483193409 -150.284919684812
71.95014897291492 110.60788894635408
-38.87616399070281 -120.35550442936838
56.54744603159949 102.92691183317305
25.061807708261938 -93.96246161003481
-51.800477940321464 12.381857596333447
14.841827412337551 0.058724441118499726
30.608126973946796 -16.809926359952755
-51.00940495973846 139.92060257524514
71.52833277252745 37.415882664168635
59.28755284279339 141.63233717977118
-83.39809276046476 62.89235647366573
-48.867284101314986 -152.74403553475787
2.4078020426233024 76.49082370114388
76.92074611712496 108.99530108602073
-13.738344592679738 90.85597978552096
-56.38276406148123 54.491826712702334
78.0097758362352 -83.83704932241267
-58.6869788140237 67.4404037004071
-13.27503008225419 93.35619741870443
-68.89537066682458 97.89695630048038
-55.68534371448119 -83.01325696610735
5.358728050468557 -65.64605540553929
-63.41609859241662 -171.34396684522505
-84.9447022158755 152.58144061766416
10.75658136628546 105.72785756825147
-84.1456044266541 12.287589079304098
-73.11784844096135 -75.9381739918433
49.28422307969788 34.32607224107326
-34.40286396298479 107.45755391494527
-10.031714021482145 -64.82722956630084
78.65005958736921 -142.50359750053087
74.58038451353343 -59.18751173209631
4.258105632027139 107.9074656972416
-2.136199984150366 -122.15388418494803
-34.89079180153114 -177.6345189984789
-71.66749974115656 -144.39650252410127
-13.210885993842979 -66.25167985079631
-5.29996979964352 -96.66894659201844
-9.211120046901655 173.24590061385595
-5.8646272924303275 77.39949689925089
-13.849800690857535 -116.25169950628505
-42.037132700900884 -172.69802464201672
-2.5027995011246134 -163.65427455419294
57.05997160454913 67.9908473740397
-21.08967164903757 140.18000575192605
-54.79979441841114 54.898872416022925
47.94561641885079 9.578958137027342
-66.24472247859478 -32.5065674921328
-66.27324354305497 -4.250360928753082
77.56865214649517 57.203167305416855
81.54932797699485 27.786596571610517
30.158948257612337 -122.07839917503019
-57.55996973366551 -166.46790965790015
-51.05259729360128 -179.25395026648675
-88.1611440504665 -163.74736882620283
56.400303028936406 52.37186729131014
61.06194109726391 145.67209819177572
-89.241500978098 89.89314726788268
-50.61677683331204 -88.77264173995628
-7.541153427728517 172.51827990480518
81.78085958128085 -109.95921035912238
-6.857981131548442 161.69659996283195
14.494966889868337 -37.662984510369995
48.91751830777142 106.1886337149021
-24.008148160613544 -93.19474810701895
-40.03606724937274 106.95482230182193
-26.796543955822195 -174.1286946507131
-53.03115720800395 -51.866294180201095
-69.53800818039056 -20.10211472547391
-25.233471048478563 67.99133167693677
38.172402808299836 95.0061710945962
-62.86860173156263 -104.51345503960263
-2.039381550950509 168.24871054315923
27.15431034747381 127.34755224352818
-57.37910678481525 -137.6744785241799
81.04614416989321 28.21467204980368
15.04000818284915 -133.5417212249945
59.736182902286174 -106.34037104448487
-51.503508639785046 -99.17302389250963
84.72841395638116 53.746110441381944
-79.86245718666146 -125.76815005950482
16.24191187844366 158.28966647403263
40.63983054296111 135.09015372982208
75.81397466104326 -29.68862982542646
39.8585656338515 -140.06815058359157
-26.84330236573674 -164.58767675698195
-17.606102771485652 -133.60250410475962
3.381410064587598 -55.269705047963214
-78.67151487458743 128.51600952169258
-37.978119565742944 -100.77623953813219
-46.200565574464946 -166.11001501574322
-32.467015026622676 -118.89705284447945
4.17213249909625 -99.55684583465381
-14.723409617271457 12.418453976575819
-83.98595822102433 -95.7592286566654
43.75521845443362 -86.83173613170038
27.55217358894818 -110.29350892081862
49.043148482034724 1.7376808939287116
20.607855219178802 155.70564222294212
-53.45508143366558 -91.84112906520991
-62.98140087294699 151.88602247049585
76.87478835451975 41.044422646309584
0.443069499870262 -160.9260755317558
-83.00989635369028 164.0169484083833
-45.1170495057333 -60.08219298604391
-47.27602838157365 135.72223796905877
-57.513188611983175 58.98136643332731
50.153446071890215 -7.564122682695512
-15.680066941519826 176.75516183611506
-72.34602974785378 -136.916851199058
10.356987039034777 -27.74493945092209
25.352727655649588 -60.3185367804072
1.5457155391883362 23.007532571493016
-80.2600395726636 -57.705396380774786
87.86967471174268 -125.56514018249047
64.02904146239939 137.04821441066014
32.638555797104175 -39.32968334292295
49.46291783991259 3.754287921298186
-83.98510812660521 151.87991319539475
70.23047433435221 -162.0790793210673
-71.98358588056695 151.60740726464843
66.13325072054195 -40.23713060129003
37.914247264420226 -153.57153569225227
42.80566959101114 127.02696616448355
-73.45521050656616 50.57688350388733
-33.68353970943369 -30.089360047639104
-61.77921067938551 -136.87482501626073
76.37290925524508 31.750438918543722
23.66657073854867 -101.62629489580812
-70.12104122787775 -59.21281510040539
-64.0166349493922 -80.1558432186673
-4.828700196067359 127.01258153374948
-18.32882305168158 121.99319105048511
-27.13778232069555 82.82016075044623
11.484745089401116 -169.49836854146392
37.294357647407665 -168.8719180589402
70.58301354421161 87.92254192087779
-35.11179517778882 104.79934925808107
-29.317948636088857 44.458324985549666
63.260447068709226 -94.44582638598023
44.49312234492055 108.3141933651234
37.059708209454314 102.84885655759246
-18.984950472313358 132.52235580831933
-7.7374251894559904 -35.86933780986928
-40.44312686608372 149.85010805365994
-64.84082147644045 119.88371151052661
-39.656020945936326 83.02237417808311
79.06413363424784 -84.53229181049504
-74.9381891568602 -68.11755490056423
42.580482552201545 -5.357588338533816
-46.72786605655078 -157.81336041901793
-20.513274866982286 -143.50065607875655
-41.7908707131374 -125.71462431765576
-4.526271774448119 -28.76535412382617
9.079619414604437 90.14534610281669
53.108321909569725 -63.7915282426314
65.73041645054553 165.56352488407146
48.98525701134628 -133.2413526664719
-35.472531284164354 7.48248822195464
47.653763173908914 -40.89150854888538
-5.296068798898887 45.68854742554308
-58.995502963392596 -50.6157140284578
-60.28281339697385 156.90311426745848
-72.17174936271147 -170.19145388969608
-80.904610360581 173.21266727906317
-55.79539878022496 -95.97560711483494
65.51358481232373 25.938016217223748
82.59454242078183 -162.98338548249632
-40.81586170474816 -2.0959499550297664
-14.070691074889822 143.52429996428953
-86.17703675094631 108.86858055856209
-31.797707377618693 161.50086211706503
7.8389451343293075 40.51634708706689
72.51277514102654 -122.45374734793899
11.878493720458977 -46.191592978904
-27.03154956359672 -167.31313568168505
27.760328852172606 5.2632954833704275
4.382125868546595 55.036092353076214
-12.27901235152926 -106.00453987668041
-28.942396641336614 -6.763202317886396
-16.64557450848632 -66.7369964003272
15.571270320903508 -31.999480693147632
-64.1559966055436 38.720269255015836
-60.16253271106017 48.8485193900525
30.195113470814277 -1.0039278652548376
19.38784909230675 -62.61510690476314
-77.83056903052479 143.56569582718572
83.64901582569999 116.60259446602174
35.499377397842466 -50.817580310187765
-52.52144942334081 -51.05087656487811
-10.536416570664429 133.39837740425213
44.4816154659197 110.58509883681137
79.85367078668554 3.437866395136382
55.98842959746267 -74.24313212573604
69.17247978131843 133.1736766832555
-71.23890757426935 67.47313901800416
53.44092911043842 -144.94126330651613
-15.213804288233973 -127.73871018854248
17.503748750649578 59.66662028384525
-66.98626071479111 -15.420655584596261
19.203304938812366 -93.5220889340088
47.23080283287126 144.08274235210519
76.04879928014614 160.16784884080374
55.079284573926344 -163.8608697279428
-30.17527670849288 -13.945659984216917
66.16661330387015 170.56437908668505
18.113953300738345 69.34032367805034
6.875404212279449 -59.17981688882607
4.94283938226981 -160.08281693187706
-57.971363322946395 44.423603357179104
80.58601357929928 -36.481064565758004
59.46594028379971 -159.5682811420725
-53.514886400433156 -4.143878875487161
-22.46972185582206 -37.72916057467853
-65.23191225239027 -15.585885450495994
-3.8036915813699608 -103.43846325571505
73.79927011941632 -106.85124665987165
-26.313069738576374 -142.92562995740815
14.795529793971056 -88.9516888057329
-42.385174245535374 -142.70177088427675
-37.33078147918987 -173.30547768574183
-51.64019126541714 -178.56126677340058
13.282364471495768 -132.22299718638138
73.0666297328373 11.752069563505927
-13.516291792469701 141.46906355793823
28.187093521649572 157.4512983325434
2.6116786299492105 143.10907118205876
18.767682608394253 56.1164256419444
-54.53665895135327 87.80054462379616
5.852836853386918 -71.4065438162301
27.900885579575757 -12.292871828557708
38.02702112123839 98.7885990901886
-48.59700917634219 -19.959441335719873
60.33975087723627 -32.39442734006539
-49.6103800099622 43.63215517435037
-41.20612944010022 -66.57842125181016
75.14637187993478 106.2346836412093
-28.85235890491024 -37.06634111675754
-18.892756002505365 167.06584809633597
0.8850893775029363 -132.19178094138823
65.5312505523583 -3.757316944638802
39.6197354334613 -93.50683369749454
67.53169925683613 -75.80277223677804
25.774619663439992 121.74473619186102
49.541328479437 -134.63849317369719
16.60720668124644 136.16233574152818
64.87627598764146 -1.462567472048903
-23.023447936292484 147.49655315984484
-58.87276540803698 -64.06799216877548
-84.4088395948401 44.07686754434923
-44.115058533441655 12.738585684949726
-69.40746548989651 -85.51075509968082
48.196761350342854 13.816359489276294
4.307657540449924 108.51410375222417
-53.1459614262431 -47.35201638128447
-31.075418434931542 32.20485452682831
-32.433664952291394 -15.840778437167529
-30.425328371309263 -100.85357723579108
9.188043196540178 -141.0765151711511
86.88680053463452 -94.09214524561628
85.56583532725168 -151.14271081384248
-53.884425849729546 95.84504114207857
74.896806813095 -129.240923391908
-83.99263826445518 -64.64074878500413
39.017740934722326 -125.12578910654504
-37.96835966505965 42.71537481626004
18.60184196884306 -178.6786237595572
7.3615658500954595 29.97716627570702
-40.75261357155267 132.71109753368938
-51.51098987917781 -20.016240633545607

In [5]:
# Use the citipy module to determine city based on latitude and longitude.
from citipy import citipy

In [6]:
# Create a list for holding the cities.
cities = []
# Identify the nearest city for each latitude and longitude combination.
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name

    # If the city is unique, then we will add it to the cities list.
    if city not in cities:
        cities.append(city)
# Print the city count to confirm sufficient count.
len(cities)

582

In [7]:
# Import the requests library.
import requests

# Import the API key.
from config import weather_api_key

In [8]:
# Starting URL for Weather Map API Call.
url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + weather_api_key
print(url)

http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=b862ba636d2dbab6fec3a658d085195d

In [9]:
# Import the time library and the datetime module from the datetime library 
import time
from datetime import datetime

In [10]:
# Create an empty list to hold the weather data.
city_data = []
# Print the beginning of the logging.
print("Beginning Data Retrieval     ")
print("-----------------------------")

# Create counters.
record_count = 1
set_count = 1

# Loop through all the cities in the list.
for i, city in enumerate(cities):

    # Group cities in sets of 50 for logging purposes.
    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 1
        time.sleep(60)

    # Create endpoint URL with each city.
    city_url = url + "&q=" + city.replace(" ","+")

    # Log the URL, record, and set numbers and the city.
    print(f"Processing Record {record_count} of Set {set_count} | {city}")
    # Add 1 to the record count.
    record_count += 1
    
    # Run an API request for each of the cities.
    try:
        # Parse the JSON and retrieve data.
        city_weather = requests.get(city_url).json()
        # Parse out the needed data.
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_country = city_weather["sys"]["country"]
        # Convert the date to ISO standard.
        city_date = datetime.utcfromtimestamp(city_weather["dt"]).strftime('%Y-%m-%d %H:%M:%S')
        # Append the city information into city_data list.
        city_data.append({"City": city.title(),
                          "Lat": city_lat,
                          "Lng": city_lng,
                          "Max Temp": city_max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Country": city_country,
                          "Date": city_date})

# If an error is experienced, skip the city.
    except:
        print("City not found. Skipping...")
        pass

# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Beginning Data Retrieval
-----------------------------
Processing Record 1 of Set 1 | inhambane
Processing Record 2 of Set 1 | namtsy
Processing Record 3 of Set 1 | raga
Processing Record 4 of Set 1 | salalah
Processing Record 5 of Set 1 | tobermory
Processing Record 6 of Set 1 | port alfred
Processing Record 7 of Set 1 | borba
Processing Record 8 of Set 1 | jalu
Processing Record 9 of Set 1 | sakaiminato
Processing Record 10 of Set 1 | bredasdorp
Processing Record 11 of Set 1 | carnarvon
Processing Record 12 of Set 1 | bambous virieux
Processing Record 13 of Set 1 | saint-philippe
Processing Record 14 of Set 1 | smithers
Processing Record 15 of Set 1 | avera
Processing Record 16 of Set 1 | lucea
Processing Record 17 of Set 1 | georgetown
Processing Record 18 of Set 1 | qaanaaq
Processing Record 19 of Set 1 | ushuaia
Processing Record 20 of Set 1 | kaitangata
Processing Record 21 of Set 1 | hamilton
Processing Record 22 of Set 1 | warqla
City not found. Skipping...
Processing Record 23 of Set 1 | kahului
Processing Record 24 of Set 1 | hithadhoo
Processing Record 25 of Set 1 | benghazi
Processing Record 26 of Set 1 | kailua
Processing Record 27 of Set 1 | punta arenas
Processing Record 28 of Set 1 | puerto ayora
Processing Record 29 of Set 1 | illoqqortoormiut
City not found. Skipping...
Processing Record 30 of Set 1 | lompoc
Processing Record 31 of Set 1 | butaritari
Processing Record 32 of Set 1 | kupang
Processing Record 33 of Set 1 | thompson
Processing Record 34 of Set 1 | sokol
Processing Record 35 of Set 1 | albany
Processing Record 36 of Set 1 | hermanus
Processing Record 37 of Set 1 | taolanaro
City not found. Skipping...
Processing Record 38 of Set 1 | victoria
Processing Record 39 of Set 1 | paytug
City not found. Skipping...
Processing Record 40 of Set 1 | mlimba
Processing Record 41 of Set 1 | kavieng
Processing Record 42 of Set 1 | hilo
Processing Record 43 of Set 1 | sao joao da barra
Processing Record 44 of Set 1 | jamestown
Processing Record 45 of Set 1 | mergui
City not found. Skipping...
Processing Record 46 of Set 1 | barrow
Processing Record 47 of Set 1 | busselton
Processing Record 48 of Set 1 | rikitea
Processing Record 49 of Set 1 | east london
Processing Record 50 of Set 1 | kapaa
Processing Record 1 of Set 2 | poddorye
Processing Record 2 of Set 2 | darhan
Processing Record 3 of Set 2 | tasiilaq
Processing Record 4 of Set 2 | saint-pascal
City not found. Skipping...
Processing Record 5 of Set 2 | bluff
Processing Record 6 of Set 2 | upernavik
Processing Record 7 of Set 2 | oildale
Processing Record 8 of Set 2 | kalianget
Processing Record 9 of Set 2 | flin flon
Processing Record 10 of Set 2 | flinders
Processing Record 11 of Set 2 | mastic beach
Processing Record 12 of Set 2 | grindavik
Processing Record 13 of Set 2 | avarua
Processing Record 14 of Set 2 | grand river south east
City not found. Skipping...
Processing Record 15 of Set 2 | aksu
Processing Record 16 of Set 2 | isangel
Processing Record 17 of Set 2 | mount gambier
Processing Record 18 of Set 2 | hobart
Processing Record 19 of Set 2 | maun
Processing Record 20 of Set 2 | zachagansk
City not found. Skipping...
Processing Record 21 of Set 2 | komsomolskiy
Processing Record 22 of Set 2 | coquimbo
Processing Record 23 of Set 2 | dikson
Processing Record 24 of Set 2 | castro
Processing Record 25 of Set 2 | provideniya
Processing Record 26 of Set 2 | poum
Processing Record 27 of Set 2 | mariental
Processing Record 28 of Set 2 | quatre cocos
Processing Record 29 of Set 2 | aykhal
Processing Record 30 of Set 2 | broome
Processing Record 31 of Set 2 | camden
Processing Record 32 of Set 2 | strezhevoy
Processing Record 33 of Set 2 | mataura
Processing Record 34 of Set 2 | ponta do sol
Processing Record 35 of Set 2 | vaini
Processing Record 36 of Set 2 | inuvik
Processing Record 37 of Set 2 | mahebourg
Processing Record 38 of Set 2 | attawapiskat
City not found. Skipping...
Processing Record 39 of Set 2 | sao jose da coroa grande
Processing Record 40 of Set 2 | mount isa
Processing Record 41 of Set 2 | sinkat
City not found. Skipping...
Processing Record 42 of Set 2 | saint-augustin
Processing Record 43 of Set 2 | chokurdakh
Processing Record 44 of Set 2 | cape town
Processing Record 45 of Set 2 | weatherford
Processing Record 46 of Set 2 | lolua
City not found. Skipping...
Processing Record 47 of Set 2 | sobolevo
Processing Record 48 of Set 2 | severo-kurilsk
Processing Record 49 of Set 2 | lorengau
Processing Record 50 of Set 2 | cabo san lucas
Processing Record 1 of Set 3 | matara
Processing Record 2 of Set 3 | kismayo
Processing Record 3 of Set 3 | port elizabeth
Processing Record 4 of Set 3 | belushya guba
City not found. Skipping...
Processing Record 5 of Set 3 | cururupu
Processing Record 6 of Set 3 | pisco
Processing Record 7 of Set 3 | abha
Processing Record 8 of Set 3 | gravelbourg
Processing Record 9 of Set 3 | sembakung
Processing Record 10 of Set 3 | umm kaddadah
Processing Record 11 of Set 3 | damghan
Processing Record 12 of Set 3 | zyryanka
Processing Record 13 of Set 3 | barentsburg
City not found. Skipping...
Processing Record 14 of Set 3 | sioux lookout
Processing Record 15 of Set 3 | vardo
Processing Record 16 of Set 3 | jackson
Processing Record 17 of Set 3 | fortuna
Processing Record 18 of Set 3 | manoharpur
Processing Record 19 of Set 3 | los llanos de aridane
Processing Record 20 of Set 3 | auki
Processing Record 21 of Set 3 | arraial do cabo
Processing Record 22 of Set 3 | nuevo progreso
Processing Record 23 of Set 3 | mehamn
Processing Record 24 of Set 3 | bur gabo
City not found. Skipping...
Processing Record 25 of Set 3 | tamandare
Processing Record 26 of Set 3 | okha
Processing Record 27 of Set 3 | bethel
Processing Record 28 of Set 3 | barao de melgaco
Processing Record 29 of Set 3 | nanortalik
Processing Record 30 of Set 3 | nemuro
Processing Record 31 of Set 3 | ugoofaaru
Processing Record 32 of Set 3 | aloleng
Processing Record 33 of Set 3 | kodiak
Processing Record 34 of Set 3 | te anau
Processing Record 35 of Set 3 | lerwick
Processing Record 36 of Set 3 | morro bay
Processing Record 37 of Set 3 | solovetskiy
City not found. Skipping...
Processing Record 38 of Set 3 | gat
Processing Record 39 of Set 3 | bundaberg
Processing Record 40 of Set 3 | constantine
Processing Record 41 of Set 3 | pacific grove
Processing Record 42 of Set 3 | hami
Processing Record 43 of Set 3 | okhotsk
Processing Record 44 of Set 3 | richards bay
Processing Record 45 of Set 3 | pudozh
Processing Record 46 of Set 3 | tukrah
Processing Record 47 of Set 3 | ulaanbaatar
Processing Record 48 of Set 3 | touros
Processing Record 49 of Set 3 | miramar
Processing Record 50 of Set 3 | ribeira grande
Processing Record 1 of Set 4 | meulaboh
Processing Record 2 of Set 4 | khatanga
Processing Record 3 of Set 4 | ilulissat
Processing Record 4 of Set 4 | moerai
Processing Record 5 of Set 4 | san patricio
Processing Record 6 of Set 4 | aklavik
Processing Record 7 of Set 4 | tarbagatay
Processing Record 8 of Set 4 | chicama
Processing Record 9 of Set 4 | umzimvubu
City not found. Skipping...
Processing Record 10 of Set 4 | mao
Processing Record 11 of Set 4 | asau
Processing Record 12 of Set 4 | oranjemund
Processing Record 13 of Set 4 | papara
Processing Record 14 of Set 4 | saskylakh
Processing Record 15 of Set 4 | vidim
Processing Record 16 of Set 4 | matamoros
Processing Record 17 of Set 4 | gorom-gorom
Processing Record 18 of Set 4 | canico
Processing Record 19 of Set 4 | new norfolk
Processing Record 20 of Set 4 | tumannyy
City not found. Skipping...
Processing Record 21 of Set 4 | muli
Processing Record 22 of Set 4 | bengkulu
Processing Record 23 of Set 4 | puerto ayacucho
Processing Record 24 of Set 4 | svay rieng
Processing Record 25 of Set 4 | novi sanzhary
Processing Record 26 of Set 4 | guajara-mirim
City not found. Skipping...
Processing Record 27 of Set 4 | pemangkat
Processing Record 28 of Set 4 | atuona
Processing Record 29 of Set 4 | santa rosa
Processing Record 30 of Set 4 | samusu
City not found. Skipping...
Processing Record 31 of Set 4 | yurginskoye
Processing Record 32 of Set 4 | weingarten
Processing Record 33 of Set 4 | mozhga
Processing Record 34 of Set 4 | kadykchan
City not found. Skipping...
Processing Record 35 of Set 4 | yellowknife

Processing Record 36 of Set 4 | porto novo
Processing Record 37 of Set 4 | necochea
Processing Record 38 of Set 4 | mar del plata
Processing Record 39 of Set 4 | yumen
Processing Record 40 of Set 4 | tabiauea
City not found. Skipping...
Processing Record 41 of Set 4 | nago
Processing Record 42 of Set 4 | la ronge
Processing Record 43 of Set 4 | preobrazheniye
Processing Record 44 of Set 4 | grand-santi
Processing Record 45 of Set 4 | lebu
Processing Record 46 of Set 4 | namibe
Processing Record 47 of Set 4 | muskegon
Processing Record 48 of Set 4 | vicam
Processing Record 49 of Set 4 | limay
Processing Record 50 of Set 4 | katsuura
Processing Record 1 of Set 5 | ostrovnoy
Processing Record 2 of Set 5 | viedma
Processing Record 3 of Set 5 | portland
Processing Record 4 of Set 5 | youghal
Processing Record 5 of Set 5 | sao filipe
Processing Record 6 of Set 5 | the valley
Processing Record 7 of Set 5 | basoko
Processing Record 8 of Set 5 | tuktoyaktuk
Processing Record 9 of Set 5 | khandyga
Processing Record 10 of Set 5 | laon
Processing Record 11 of Set 5 | huadian
Processing Record 12 of Set 5 | charcas
Processing Record 13 of Set 5 | ambon
Processing Record 14 of Set 5 | talnakh
Processing Record 15 of Set 5 | tsihombe
City not found. Skipping...
Processing Record 16 of Set 5 | wuwei
Processing Record 17 of Set 5 | katherine
Processing Record 18 of Set 5 | surubim
Processing Record 19 of Set 5 | launceston
Processing Record 20 of Set 5 | leon
Processing Record 21 of Set 5 | tautira
Processing Record 22 of Set 5 | cabedelo
Processing Record 23 of Set 5 | port blair
Processing Record 24 of Set 5 | havre-saint-pierre
Processing Record 25 of Set 5 | bilibino
Processing Record 26 of Set 5 | port hardy
Processing Record 27 of Set 5 | saldanha
Processing Record 28 of Set 5 | torbay
Processing Record 29 of Set 5 | tuatapere
Processing Record 30 of Set 5 | haukipudas
Processing Record 31 of Set 5 | mareeba
Processing Record 32 of Set 5 | ballina
Processing Record 33 of Set 5 | ginir
Processing Record 34 of Set 5 | norman wells
Processing Record 35 of Set 5 | cayenne
Processing Record 36 of Set 5 | alofi
Processing Record 37 of Set 5 | eyl
Processing Record 38 of Set 5 | quime
Processing Record 39 of Set 5 | adrar
Processing Record 40 of Set 5 | maningrida
Processing Record 41 of Set 5 | erenhot
Processing Record 42 of Set 5 | chapais
Processing Record 43 of Set 5 | verkhoyansk
Processing Record 44 of Set 5 | sur
Processing Record 45 of Set 5 | paraiso
Processing Record 46 of Set 5 | novikovo
Processing Record 47 of Set 5 | cherskiy
Processing Record 48 of Set 5 | pevek
Processing Record 49 of Set 5 | veraval
Processing Record 50 of Set 5 | bartica
Processing Record 1 of Set 6 | guarapari
Processing Record 2 of Set 6 | san agustin
Processing Record 3 of Set 6 | guerrero negro
Processing Record 4 of Set 6 | gravdal
Processing Record 5 of Set 6 | daru
Processing Record 6 of Set 6 | hasaki
Processing Record 7 of Set 6 | vanimo
Processing Record 8 of Set 6 | paz de ariporo
City not found. Skipping...
Processing Record 9 of Set 6 | arrecife
Processing Record 10 of Set 6 | jiuquan
Processing Record 11 of Set 6 | puerto madryn
Processing Record 12 of Set 6 | vila
Processing Record 13 of Set 6 | klaksvik
Processing Record 14 of Set 6 | marshall
Processing Record 15 of Set 6 | clyde river
Processing Record 16 of Set 6 | keelung
Processing Record 17 of Set 6 | prince rupert
Processing Record 18 of Set 6 | airai
Processing Record 19 of Set 6 | brae
Processing Record 20 of Set 6 | emerald
Processing Record 21 of Set 6 | grieskirchen
Processing Record 22 of Set 6 | scottsburgh
City not found. Skipping...
Processing Record 23 of Set 6 | ler
Processing Record 24 of Set 6 | port lincoln
Processing Record 25 of Set 6 | elizabeth city
Processing Record 26 of Set 6 | san ignacio de sabaneta
City not found. Skipping...
Processing Record 27 of Set 6 | roebourne
Processing Record 28 of Set 6 | dapaong
Processing Record 29 of Set 6 | karibib
Processing Record 30 of Set 6 | chokwe
Processing Record 31 of Set 6 | rafai
Processing Record 32 of Set 6 | grand forks
Processing Record 33 of Set 6 | santa maria
Processing Record 34 of Set 6 | ancud
Processing Record 35 of Set 6 | strehaia
Processing Record 36 of Set 6 | nchelenge
Processing Record 37 of Set 6 | fare
Processing Record 38 of Set 6 | port macquarie
Processing Record 39 of Set 6 | karkaralinsk
City not found. Skipping...
Processing Record 40 of Set 6 | ailigandi
Processing Record 41 of Set 6 | laguna
Processing Record 42 of Set 6 | manokwari
Processing Record 43 of Set 6 | whitley bay
Processing Record 44 of Set 6 | iqaluit
Processing Record 45 of Set 6 | ouadda
Processing Record 46 of Set 6 | dunedin
Processing Record 47 of Set 6 | eureka
Processing Record 48 of Set 6 | imbituba
Processing Record 49 of Set 6 | billings
Processing Record 50 of Set 6 | cidreira
Processing Record 1 of Set 7 | nsanje
Processing Record 2 of Set 7 | raymondville
Processing Record 3 of Set 7 | denpasar
Processing Record 4 of Set 7 | alta gracia
Processing Record 5 of Set 7 | neyshabur
Processing Record 6 of Set 7 | goderich
Processing Record 7 of Set 7 | arang
Processing Record 8 of Set 7 | mocambique
City not found. Skipping...
Processing Record 9 of Set 7 | gazanjyk
Processing Record 10 of Set 7 | longyearbyen
Processing Record 11 of Set 7 | tefe
Processing Record 12 of Set 7 | verkhniye kigi
Processing Record 13 of Set 7 | puri
Processing Record 14 of Set 7 | jiazi
Processing Record 15 of Set 7 | road town
Processing Record 16 of Set 7 | san juan
Processing Record 17 of Set 7 | ketchikan
Processing Record 18 of Set 7 | lyngseidet
Processing Record 19 of Set 7 | san jeronimo
Processing Record 20 of Set 7 | kloulklubed
Processing Record 21 of Set 7 | dabola
Processing Record 22 of Set 7 | yurga
Processing Record 23 of Set 7 | ponta delgada
Processing Record 24 of Set 7 | vestmannaeyjar
Processing Record 25 of Set 7 | tutoia
Processing Record 26 of Set 7 | verkhnyaya inta
Processing Record 27 of Set 7 | angangxi
City not found. Skipping...
Processing Record 28 of Set 7 | rovaniemi
Processing Record 29 of Set 7 | ulladulla
Processing Record 30 of Set 7 | turek
Processing Record 31 of Set 7 | nikolskoye
Processing Record 32 of Set 7 | beringovskiy
Processing Record 33 of Set 7 | gornozavodsk
Processing Record 34 of Set 7 | vila franca do campo
Processing Record 35 of Set 7 | kalanguy
Processing Record 36 of Set 7 | kruisfontein
Processing Record 37 of Set 7 | dahod
Processing Record 38 of Set 7 | lata
Processing Record 39 of Set 7 | karratha
Processing Record 40 of Set 7 | tuysarkan
City not found. Skipping...
Processing Record 41 of Set 7 | fairbanks
Processing Record 42 of Set 7 | amarillo
Processing Record 43 of Set 7 | el alto
Processing Record 44 of Set 7 | sentyabrskiy
City not found. Skipping...
Processing Record 45 of Set 7 | marsh harbour
Processing Record 46 of Set 7 | faridpur
Processing Record 47 of Set 7 | itoman
Processing Record 48 of Set 7 | mys shmidta
City not found. Skipping...
Processing Record 49 of Set 7 | narsaq
Processing Record 50 of Set 7 | tananger
Processing Record 1 of Set 8 | aksarka
Processing Record 2 of Set 8 | manta
Processing Record 3 of Set 8 | ornskoldsvik
Processing Record 4 of Set 8 | kushmurun
Processing Record 5 of Set 8 | magway
Processing Record 6 of Set 8 | tessalit
Processing Record 7 of Set 8 | tabarqah
City not found. Skipping...
Processing Record 8 of Set 8 | coihaique
Processing Record 9 of Set 8 | sabang
Processing Record 10 of Set 8 | lemoore
Processing Record 11 of Set 8 | wielun
Processing Record 12 of Set 8 | muzaffarabad
Processing Record 13 of Set 8 | sovetskiy
Processing Record 14 of Set 8 | peniche
Processing Record 15 of Set 8 | plettenberg bay
Processing Record 16 of Set 8 | dongfeng
Processing Record 17 of Set 8 | harper
Processing Record 18 of Set 8 | lasa
Processing Record 19 of Set 8 | petrovskoye
Processing Record 20 of Set 8 | lexington
Processing Record 21 of Set 8 | nizhneyansk
City not found. Skipping...
Processing Record 22 of Set 8 | nguiu
City not found. Skipping...
Processing Record 23 of Set 8 | vaitupu
City not found. Skipping...
Processing Record 24 of Set 8 | yulara

Processing Record 25 of Set 8 | kulhudhuffushi
Processing Record 26 of Set 8 | rawson
Processing Record 27 of Set 8 | constitucion
Processing Record 28 of Set 8 | sarangani
Processing Record 29 of Set 8 | bontang
Processing Record 30 of Set 8 | kristinehamn
Processing Record 31 of Set 8 | hay river
Processing Record 32 of Set 8 | ngukurr
City not found. Skipping...
Processing Record 33 of Set 8 | zadar
Processing Record 34 of Set 8 | namatanai
Processing Record 35 of Set 8 | acajutla
Processing Record 36 of Set 8 | bambanglipuro
Processing Record 37 of Set 8 | meghri
Processing Record 38 of Set 8 | roma
Processing Record 39 of Set 8 | montijo
Processing Record 40 of Set 8 | gizo
Processing Record 41 of Set 8 | makaha
Processing Record 42 of Set 8 | sorland
Processing Record 43 of Set 8 | morondava
Processing Record 44 of Set 8 | falealupo
City not found. Skipping...
Processing Record 45 of Set 8 | skalistyy
City not found. Skipping...
Processing Record 46 of Set 8 | changli
Processing Record 47 of Set 8 | ust-tsilma
Processing Record 48 of Set 8 | palabuhanratu
City not found. Skipping...
Processing Record 49 of Set 8 | cockburn town
Processing Record 50 of Set 8 | lagoa
Processing Record 1 of Set 9 | soe
Processing Record 2 of Set 9 | ajdabiya
Processing Record 3 of Set 9 | poya
Processing Record 4 of Set 9 | chuy
Processing Record 5 of Set 9 | ningxiang
Processing Record 6 of Set 9 | shahr-e kord
Processing Record 7 of Set 9 | zabaykalsk
Processing Record 8 of Set 9 | faya
Processing Record 9 of Set 9 | chingirlau
Processing Record 10 of Set 9 | moose factory
Processing Record 11 of Set 9 | saint-joseph
Processing Record 12 of Set 9 | bubaque
Processing Record 13 of Set 9 | arlit
Processing Record 14 of Set 9 | natitingou
Processing Record 15 of Set 9 | aflu
City not found. Skipping...
Processing Record 16 of Set 9 | jieshi
Processing Record 17 of Set 9 | champoton
Processing Record 18 of Set 9 | souillac
Processing Record 19 of Set 9 | akdepe
Processing Record 20 of Set 9 | amderma
City not found. Skipping...
Processing Record 21 of Set 9 | zaysan
Processing Record 22 of Set 9 | palora
Processing Record 23 of Set 9 | luderitz
Processing Record 24 of Set 9 | boyolangu
Processing Record 25 of Set 9 | inderborskiy
City not found. Skipping...
Processing Record 26 of Set 9 | xinxiang
Processing Record 27 of Set 9 | esperance
Processing Record 28 of Set 9 | tual
Processing Record 29 of Set 9 | tiksi
Processing Record 30 of Set 9 | port-gentil
Processing Record 31 of Set 9 | namwala
Processing Record 32 of Set 9 | skuratovskiy
Processing Record 33 of Set 9 | languyan
Processing Record 34 of Set 9 | qasigiannguit
Processing Record 35 of Set 9 | bouca
Processing Record 36 of Set 9 | atar
Processing Record 37 of Set 9 | walvis bay
Processing Record 38 of Set 9 | marrakesh
Processing Record 39 of Set 9 | nishihara
Processing Record 40 of Set 9 | mildura
Processing Record 41 of Set 9 | sokolo
Processing Record 42 of Set 9 | artyk
City not found. Skipping...
Processing Record 43 of Set 9 | saint-pierre
Processing Record 44 of Set 9 | dingle
Processing Record 45 of Set 9 | stephenville
Processing Record 46 of Set 9 | saint george
Processing Record 47 of Set 9 | codrington
Processing Record 48 of Set 9 | port hedland
Processing Record 49 of Set 9 | sola
Processing Record 50 of Set 9 | kapoeta
Processing Record 1 of Set 10 | praia da vitoria
Processing Record 2 of Set 10 | ullapool
Processing Record 3 of Set 10 | san jose
Processing Record 4 of Set 10 | grand gaube
Processing Record 5 of Set 10 | monrovia
Processing Record 6 of Set 10 | numata
Processing Record 7 of Set 10 | margate
Processing Record 8 of Set 10 | broken hill
Processing Record 9 of Set 10 | hofn
Processing Record 10 of Set 10 | de panne
Processing Record 11 of Set 10 | geraldton
Processing Record 12 of Set 10 | whitehorse
Processing Record 13 of Set 10 | baruun-urt
Processing Record 14 of Set 10 | parabel
Processing Record 15 of Set 10 | san ignacio
Processing Record 16 of Set 10 | axim
Processing Record 17 of Set 10 | kidal
Processing Record 18 of Set 10 | egvekinot
Processing Record 19 of Set 10 | tazovskiy
Processing Record 20 of Set 10 | faanui
Processing Record 21 of Set 10 | san lawrenz
Processing Record 22 of Set 10 | juruti
Processing Record 23 of Set 10 | warrenville
Processing Record 24 of Set 10 | arman
Processing Record 25 of Set 10 | colwyn bay
Processing Record 26 of Set 10 | senj
Processing Record 27 of Set 10 | riaba
City not found. Skipping...
Processing Record 28 of Set 10 | guozhen
Processing Record 29 of Set 10 | pangnirtung
Processing Record 30 of Set 10 | gisborne
Processing Record 31 of Set 10 | newcastle
Processing Record 32 of Set 10 | askim
Processing Record 33 of Set 10 | neka
Processing Record 34 of Set 10 | pavlovsk
Processing Record 35 of Set 10 | batticaloa
Processing Record 36 of Set 10 | ijui
Processing Record 37 of Set 10 | skjervoy
Processing Record 38 of Set 10 | nadym
Processing Record 39 of Set 10 | swift current
Processing Record 40 of Set 10 | zhongshu
Processing Record 41 of Set 10 | half moon bay
Processing Record 42 of Set 10 | pangkalanbuun
Processing Record 43 of Set 10 | louisbourg
City not found. Skipping...
Processing Record 44 of Set 10 | olinda
Processing Record 45 of Set 10 | takanabe
Processing Record 46 of Set 10 | naryan-mar
Processing Record 47 of Set 10 | samalaeulu
City not found. Skipping...
Processing Record 48 of Set 10 | jizan
Processing Record 49 of Set 10 | berlevag
Processing Record 50 of Set 10 | ormara
Processing Record 1 of Set 11 | mangochi
Processing Record 2 of Set 11 | malakal
Processing Record 3 of Set 11 | jiaocheng
Processing Record 4 of Set 11 | qaqortoq
Processing Record 5 of Set 11 | chernenko
Processing Record 6 of Set 11 | pio xii
Processing Record 7 of Set 11 | sao joao de pirabas
Processing Record 8 of Set 11 | altay
Processing Record 9 of Set 11 | torfyanoy
Processing Record 10 of Set 11 | high level
Processing Record 11 of Set 11 | satitoa
City not found. Skipping...
Processing Record 12 of Set 11 | acurenam
Processing Record 13 of Set 11 | alice springs
Processing Record 14 of Set 11 | tabou
Processing Record 15 of Set 11 | yebaishou
Processing Record 16 of Set 11 | rypefjord
Processing Record 17 of Set 11 | iberia
Processing Record 18 of Set 11 | cuicatlan
Processing Record 19 of Set 11 | salinopolis
Processing Record 20 of Set 11 | kilindoni
Processing Record 21 of Set 11 | parrita
Processing Record 22 of Set 11 | rocha
Processing Record 23 of Set 11 | pakxe
Processing Record 24 of Set 11 | nueva loja
Processing Record 25 of Set 11 | labuhan
Processing Record 26 of Set 11 | kamenskoye
City not found. Skipping...
Processing Record 27 of Set 11 | pa sang
Processing Record 28 of Set 11 | malbang
Processing Record 29 of Set 11 | ixhuatlancillo
Processing Record 30 of Set 11 | puerto del rosario
Processing Record 31 of Set 11 | les cayes
Processing Record 32 of Set 11 | algarrobo
Processing Record 33 of Set 11 | diffa
Processing Record 34 of Set 11 | hongjiang
Processing Record 35 of Set 11 | labytnangi
Processing Record 36 of Set 11 | salinas
Processing Record 37 of Set 11 | katangli
Processing Record 38 of Set 11 | taber
Processing Record 39 of Set 11 | garowe
Processing Record 40 of Set 11 | mayumba
Processing Record 41 of Set 11 | santa catalina
Processing Record 42 of Set 11 | inyonga
Processing Record 43 of Set 11 | kirishi
Processing Record 44 of Set 11 | quelimane
Processing Record 45 of Set 11 | solnechnyy
Processing Record 46 of Set 11 | fukue
Processing Record 47 of Set 11 | vryburg
Processing Record 48 of Set 11 | lakshmipur
Processing Record 49 of Set 11 | mkushi
Processing Record 50 of Set 11 | sitka
Processing Record 1 of Set 12 | yarkovo
Processing Record 2 of Set 12 | tomatlan
Processing Record 3 of Set 12 | halalo
City not found. Skipping...
Processing Record 4 of Set 12 | heihe
Processing Record 5 of Set 12 | dianopolis
City not found. Skipping...
Processing Record 6 of Set 12 | petropavlovsk-kamchatskiy
Processing Record 7 of Set 12 | anadyr
Processing Record 8 of Set 12 | port augusta
Processing Record 9 of Set 12 | mwandiga
Processing Record 10 of Set 12 | seydi
Processing Record 11 of Set 12 | krasnoselkup
Processing Record 12 of Set 12 | wulanhaote
City not found. Skipping...
Processing Record 13 of Set 12 | eskasem
City not found. Skipping...
Processing Record 14 of Set 12 | vozhega

Processing Record 15 of Set 12 | chavakkad
Processing Record 16 of Set 12 | maceio
Processing Record 17 of Set 12 | bonavista
Processing Record 18 of Set 12 | cazaje
City not found. Skipping...
Processing Record 19 of Set 12 | safaga
Processing Record 20 of Set 12 | port victoria
Processing Record 21 of Set 12 | cap malheureux
Processing Record 22 of Set 12 | boralday
Processing Record 23 of Set 12 | severnoye
Processing Record 24 of Set 12 | ahtopol
Processing Record 25 of Set 12 | andenes
Processing Record 26 of Set 12 | vostok
Processing Record 27 of Set 12 | polovragi
Processing Record 28 of Set 12 | mubi
Processing Record 29 of Set 12 | brahmapuri
City not found. Skipping...
Processing Record 30 of Set 12 | wokha
Processing Record 31 of Set 12 | lixourion
Processing Record 32 of Set 12 | mitsamiouli
-----------------------------
Data Retrieval Complete
-----------------------------

In [11]:
len(cities)

582

In [12]:
# Convert the array of dictionaries to a Pandas DataFrame.
city_data_df = pd.DataFrame(city_data)
city_data_df.head(10)

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Inhambane,-23.8650,35.3833,71.37,89,1,9.35,MZ,2022-10-04 00:59:06
1,Namtsy,62.7161,129.6658,25.79,76,100,5.91,RU,2022-10-04 00:59:07
2,Raga,8.4596,25.6780,69.19,95,100,3.87,SS,2022-10-04 00:59:07
3,Salalah,17.0151,54.0924,76.01,83,81,3.56,OM,2022-10-04 00:59:07
4,Tobermory,45.2501,-81.6665,54.82,53,100,5.28,CA,2022-10-04 00:59:07
5,Port Alfred,-33.5906,26.8910,58.17,85,100,4.00,ZA,2022-10-04 00:59:08
6,Borba,-4.3878,-59.5939,77.74,76,80,2.28,BR,2022-10-04 00:59:08
7,Jalu,29.0331,21.5482,70.48,73,0,12.12,LY,2022-10-04 00:59:08
8,Sakaiminato,35.5500,133.2333,82.33,66,85,12.82,JP,2022-10-04 00:59:09
9,Bredasdorp,-34.5322,20.0403,50.36,89,0,6.53,ZA,2022-10-04 00:59:09

In [15]:
#reorder columns
new_column_order = ["City", "Country", "Date", "Lat", "Lng", "Max Temp", "Humidity", "Cloudiness", "Wind Speed"]
city_data_df = city_data_df[new_column_order]
city_data_df.head(10)

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,Inhambane,MZ,2022-10-04 00:59:06,-23.8650,35.3833,71.37,89,1,9.35
1,Namtsy,RU,2022-10-04 00:59:07,62.7161,129.6658,25.79,76,100,5.91
2,Raga,SS,2022-10-04 00:59:07,8.4596,25.6780,69.19,95,100,3.87
3,Salalah,OM,2022-10-04 00:59:07,17.0151,54.0924,76.01,83,81,3.56
4,Tobermory,CA,2022-10-04 00:59:07,45.2501,-81.6665,54.82,53,100,5.28
5,Port Alfred,ZA,2022-10-04 00:59:08,-33.5906,26.8910,58.17,85,100,4.00
6,Borba,BR,2022-10-04 00:59:08,-4.3878,-59.5939,77.74,76,80,2.28
7,Jalu,LY,2022-10-04 00:59:08,29.0331,21.5482,70.48,73,0,12.12
8,Sakaiminato,JP,2022-10-04 00:59:09,35.5500,133.2333,82.33,66,85,12.82
9,Bredasdorp,ZA,2022-10-04 00:59:09,-34.5322,20.0403,50.36,89,0,6.53

In [17]:
# Create the output file (CSV).
output_data_file = "weather_data/cities.csv"
# Export the City_Data into a CSV.
city_data_df.to_csv(output_data_file, index_label="City_ID")